---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: amazon.aws
      - name: community.general
      - name: openstack.cloud
      - name: https://github.com/ryankwilliams/aap-toolbox.git
        type: git
  python:
    - openstacksdk
  system:
    - git [platform:rpm]
    - python3.11 [platform:rpm]
    - python3.11-devel [platform:rpm]
    - gcc [platform:rpm]
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"

options:
  package_manager_path: /usr/bin/microdnf
