---
- name: Deploy task manager application
  hosts: task_manager

  vars:
    task_manager_repo: https://github.com/ryankwilliams/task-manager.git
    task_manager_repo_branch: main
    task_manager_dir: ~/task-manager
    task_manager_url: "http://{{ ansible_facts.default_ipv4.address }}:9090"  # TODO: Get port from input

  tasks:
    - name: Install package dependencies
      become: true
      ansible.builtin.dnf:  # noqa: package-latest
        name:
          - git
          - podman
        state: latest

    - name: Clone task-manager app repository
      ansible.builtin.git:
        repo: "{{ task_manager_repo }}"
        version: "{{ task_manager_repo_branch }}"
        dest: "{{ task_manager_dir }}"
        force: true

    - name: Create podman quadlet directory
      ansible.builtin.file:
        path: "~/.config/containers/systemd"
        state: directory
        mode: "0755"

    - name: Copy task-manager podman quadlet files to quadlet directory
      ansible.builtin.copy:
        src: "{{ task_manager_dir }}/deploy/podman_quadlet"
        dest: "~/.config/containers/systemd"
        mode: "0644"
        remote_src: true

    - name: Reload systemd to generate task-manager quadlet service files
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Start task-manager-db service
      ansible.builtin.systemd:
        name: task-manager-db
        state: started
        scope: user

    - name: Start task-manager-app service
      ansible.builtin.systemd:
        name: task-manager-app
        state: started
        scope: user

    - name: Task manager app url
      ansible.builtin.debug:
        msg: "Task manager url: {{ task_manager_url }}"
