---
- name: Process task manager events
  hosts: localhost

  sources:
    - name: Listen for task manager events
      ryankwilliams.aap_toolbox.task_manager:
        url: "{{ task_manager_url }}"
        delay: 30

  rules:
    - name: Process tasks that are in a 'todo' state
      condition: event.status == "todo"
      action:
        debug:
          msg: "Handling task id: {{ event.task_id }}"
