---
- name: Process todo tasks
  hosts: localhost

  sources:
    - name: Listen for new todo tasks
      todo_app_api:
        url: "{{ app_url }}"
        delay: 30

  rules:
    - name: Process standard default todo tasks (status=todo)
      condition: event.status == "todo"
      action:
        debug:
          msg: "Handling todo task id: {{ event.task_id }}"
