---
- name: Process todo tasks
  hosts: localhost

  sources:
    - name: Poll for new todo tasks
      ryankwilliams.aap_toolbox.todo_app_api:
        url: "{{ app_url }}"
        delay: 30

  rules:
    - name: Process todo tasks in todo state
      condition: event.status == "todo"
      action:
        debug:
          msg: "Handling todo task id: {{ event.task_id }}"
