deploy_app_repo: https://github.com/ryankwilliams/task-manager.git
deploy_app_repo_branch: main
deploy_app_dir: /tmp/task-manager
deploy_app_url: "http://{{ ansible_facts.default_ipv4.address }}:9090"  # TODO: Get port from input
