---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel9:latest

dependencies:
  python:
    - ansible-rulebook==1.0.5
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - ansible.eda
      - name: https://github.com/ryankwilliams/aap-toolbox.git
        type: git
  system:
    - git [platform:rpm]
    - python3.11 [platform:rpm]
    - python3.11-devel [platform:rpm]
    - gcc [platform:rpm]
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base:
    - RUN mkdir -p /opt/builder/bin/
  append_final:
    - RUN rm -rf /usr/bin/python3 && ln -s python3.11 /usr/bin/python3
