---
- name: Create OpenStack Server
  hosts: localhost

  vars:
    server_name: "{{ lookup('ansible.builtin.env', 'SERVER_NAME', default='') }}"
    keypair_name: "{{ lookup('ansible.builtin.env', 'KEYPAIR_NAME', default='') }}"
    flavor: "{{ lookup('ansible.builtin.env', 'FLAVOR', default='') }}"
    image: "{{ lookup('ansible.builtin.env', 'IMAGE', default='') }}"
    network: "{{ lookup('ansible.builtin.env', 'NETWORK', default='') }}"
    security_group: "{{ lookup('ansible.builtin.env', 'SECURITY_GROUP', default='default') }}"

  tasks:
    - name: Validate input
      ansible.builtin.assert:
        that:
          - server_name != ""
          - keypair_name != ""

    - name: Create server
      openstack.cloud.server:
        name: "{{ server_name }}"
        key_name: "{{ keypair_name }}"
        security_groups: "{{ security_group }}"
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        network: "{{ network }}"
        timeout: 120
        state: present
        auto_ip: false
      register: server_results

    - name: Wait for server to be ready
      ansible.builtin.wait_for:
        state: started
        host: "{{ server_results['server']['addresses'][network][0]['addr'] }}"
        port: 22
        search_regex: OpenSSH
        timeout: 120
        sleep: 10

    - name: Summary
      ansible.builtin.debug:
        msg: "IP Address: {{ server_results['server']['addresses'][network][0]['addr'] }}"
