---
- name: Deploy web server
  hosts: web_server

  vars:
    server_url: "http://{{ ansible_facts.default_ipv4.address }}:80"

  vars_files:
    - vars/aws.yml
    - vars/openstack.yml

  tasks:
    - name: Validate global input
      ansible.builtin.include_tasks: tasks/validate_global_input.yml

    - name: Get aws ec2 server public ip address
      when: cloud_provider == "aws"
      ansible.builtin.include_tasks: tasks/get_aws_server_public_ip.yml

    - name: Install/configure httpd server
      become: true
      block:
        - name: Install httpd package
          ansible.builtin.dnf:  # noqa: package-latest
            name: httpd
            state: latest

        - name: Start/enable httpd service
          ansible.builtin.service:
            name: httpd
            state: started
            enabled: true

        - name: Create index.html for static page
          ansible.builtin.copy:
            dest: /var/www/html/index.html
            content: Hello World!
            mode: "0644"

    - name: Verify httpd server is available
      ansible.builtin.uri:
        url: "{{ server_url }}"
        method: GET
        return_content: true
        validate_certs: false
        status_code: 200
      register: get_result
      delegate_to: localhost

    - name: Verify content on static page
      ansible.builtin.assert:
        that: "'Hello World!' in get_result.content"
