---
- name: Deploy task manager application
  hosts: task_manager

  vars:
    deploy_type: "vm"

  tasks:
    - name: Validate required input
      ansible.builtin.assert:
        that:
          - deploy_type is defined
          - deploy_type == "vm"

    - name: Deploy task-manager
      ansible.builtin.include_role:
        name: ryankwilliams.aap_toolbox.task_manager_app
        tasks_from: vm_deploy
      when: deploy_type == "vm"
