---
- name: Provision ec2 instance
  hosts: localhost

  vars:
    cloud_provider: "{{ lookup('ansible.builtin.env', 'CLOUD_PROVIDER', default='') }}"

  tasks:
    - name: Provision ec2 instance
      ansible.builtin.include_role:
        name: ryankwilliams.aap_toolbox.vm
        tasks_from: create
      vars:
        vm_inventory_groups:
          - web_server

- name: Deploy web server
  hosts: web_server

  vars:
    cloud_provider: "{{ lookup('ansible.builtin.env', 'CLOUD_PROVIDER', default='') }}"
    region_name: "{{ lookup('ansible.builtin.env', 'AWS_REGION', default='us-east-1') }}"

  tasks:
    - name: Validate global input
      ansible.builtin.include_role:
        name: ryankwilliams.aap_toolbox.vm
        tasks_from: validate_global_input.yml

    - name: Get aws ec2 server public ip address
      when: cloud_provider == "aws"
      ansible.builtin.include_tasks: tasks/get_aws_server_public_ip.yml
